services:
  patrick-im-server:
    image: ${PATRICK_IM_IMAGE:-patrick-im-server:latest}
    container_name: patrick-im-server
    restart: unless-stopped
    env_file:
      - ../backend/server/.env
    ports:
      - "127.0.0.1:5800:5800"
    volumes:
      - ../data/files:/app/data/files
    networks:
      - app

networks:
  app:
    external: true
    name: ${PATRICK_IM_DOCKER_NETWORK:-1panel-network}
